default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: viacartorios
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: vagas_dev_italo_miranda